name: Publish a new release on pkg.go.dev

on:
  push:
    tags:
      - v[0-9]+.**

permissions:
  contents: read

jobs:
  publish_release:
    name: Publish a new release on pkg.go.dev
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version-file: ./go.mod

      - name: Publish on pkg.go.dev
        run: GOPROXY=proxy.golang.org go list -m github.com/np-guard/cloud-resource-collector@${{ github.ref_name }}
